api-version: 2024-02-02-preview
location: {{ .Env.AZURE_LOCATION }}
identity:
  type: UserAssigned
  userAssignedIdentities:
    ? "{{ .Env.AZURE_CONTAINER_REGISTRY_MANAGED_IDENTITY_ID }}"
    : {}
properties:
  environmentId: {{ .Env.AZURE_CONTAINER_APPS_ENVIRONMENT_ID }}
  configuration:
    activeRevisionsMode: single
    runtime:
      dotnet:
        autoConfigureDataProtection: true
    ingress:
      external: false
      targetPort: 8000
      transport: http
      allowInsecure: true
    registries:
      - server: {{ .Env.AZURE_CONTAINER_REGISTRY_ENDPOINT }}
        identity: {{ .Env.AZURE_CONTAINER_REGISTRY_MANAGED_IDENTITY_ID }}
    secrets:
      - name: applicationinsights-connection-string
        value: '{{ .Env.APPINSIGHTS_APPINSIGHTSCONNECTIONSTRING }}'
  template:
    volumes:
      - name: apiserver-hfmodelcache
        storageType: AzureFile
        storageName: {{ .Env.SERVICE_APISERVER_VOLUME_HFMODELCACHE_NAME }} 
    containers:
      - image: {{ .Image }}
        name: apiserver
        env:
          - name: AZURE_CLIENT_ID
            value: {{ .Env.MANAGED_IDENTITY_CLIENT_ID }}
          - name: HF_HOME
            value: /root/.cache/huggingface
          - name: PYTHONUNBUFFERED
            value: "1"
          - name: APPLICATIONINSIGHTS_CONNECTION_STRING
            secretRef: applicationinsights-connection-string
        volumeMounts:
          - volumeName: apiserver-hfmodelcache
            mountPath: /root/.cache/huggingface
    scale:
      minReplicas: 1
tags:
  azd-service-name: apiserver
  aspire-resource-name: apiserver
